### PR TITLE
Added front-end text-limiting functionality

### PR DESCRIPTION
**Pull request by d2roth**
Hey @rilwis 
This is a great plugin but it doesn't limit the output on the frontend. I was looking for a way to limit the text on the front end even if someone bypassed the js limiter. I created this fork to accomplish just that.

If you have any questions/suggestions feel free to ask.
Thanks,

### CODE REVIEW

**Comment by rilwis** [comment]
Thanks a lot for your contribution. Can you please change the hook to `rwmb_get_value` and `rwmb_the_value` instead? I decided to change these names to make them more meaningful. `get_field` might be confused for getting field's parameter.

**Comment by d2roth** [comment]
I am glad to help out. I am slightly confused though about your request to change the hooks to `rwmb_get_value` and `rwmb_the_value`. Those hooks do not seem to appear anywhere in Meta Box 4.8.1. I am thinking though you meant the function names so I have changed them.

**Comment by d2roth** [comment]
Oh also what would the plugin version change to? would it simply be 1.1.0?

**Comment by rilwis** [comment]
Yes, I think so 1.1.0 sounds good.

**Comment by rilwis** [comment]
Oh, I forget to change the hook in 4.8.1. Will do it now :)

**Comment by d2roth** [comment]
I have bumped the version number and changed the filter names. I am just wondering though if you change the filter name wouldn't it break existing plugins that hook into rwmb_get_field and rwmb_the_field?

**Comment by rilwis** [comment]
Hmm, these filters aren't public yet as they're still in the development. I guess not many people are using it and I think it's safe to change filter names.

PS: I already did that in the development version.

**Comment by d2roth** [comment]
Ok. It is your call. So for this to work now I will need to update my plugin to the development version right?

Also would it make sense to add a conditional check around those 2 filters and check the RWMB_VER to see if it is 4.8.1 or before and then hook into the old filters? I just think you have such a great product and making it backwards compatible would be a benefit.

**Comment by rilwis** [comment]
OK, no problem. I will add that now.

**Comment by rilwis** [comment]
Done. Just add backward compatibility [here](https://github.com/rilwis/meta-box/commit/1bf516e9068996549cc33353065148f12d11d64c)

**Pull request merged**
